# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run stryker
    - run: ls
    - run: "curl -X PUT \
          https://dashboard.stryker-mutator.io/api/reports/${{ env.GITHUB_REPOSITORY }}/${{ env.GITHUB_REF }} \
          -H 'Content-Type: application/json' \
          -H 'Host: dashboard.stryker-mutator.io' \
          -H 'X-Api-Key: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}' \
          -d @mutation-testing-report.json"
